runtime: python37
api_version: 1
threadsafe: true


# [START handlers]
handlers:
# Telegram web hook URLs
- url: /TG.*
  script: bot.app

# Other URLs - allowed only for gcloud project admins (Google login)
- url: /.*
  script: bot.app
  login: admin
